#!/usr/bin/env python3
"""Generate merge/fixtures.json -- base + pak inputs to expected merged output.

Each case carries three things:

  inputs               a release base catalog and one or more contributors
  expect_diagnostics   the reason slugs a HUMAN asserts, hand-written here
  expected             the merged catalog, computed by content_model.merge()

The hand-written `expect_diagnostics` is what keeps this honest. The
`expected` block is generated, so on its own it would agree with the model by
construction; the diagnostics list does not, and a model change that alters
which contributions survive shows up as a failed assertion rather than a
silently-regenerated expectation. The generated bytes still earn their place:
Jawaka's C compiler must reproduce them exactly, and any change to them is
visible in review as a diff.

Run: python3 gen_merge_fixtures.py
"""
from __future__ import annotations

import json
import os
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(HERE)
sys.path.insert(0, HERE)

import canonical  # noqa: E402
import content_model  # noqa: E402

OUT = os.path.join(ROOT, "merge", "fixtures.json")

# A stand-in for the release defaults: small enough to read, with the exact
# namespace values the collision cases need to hit.
BASE = {
    "platform": "mlp1",
    "systems": [
        {
            "id": "SNES",
            "name": "Super Nintendo",
            "patterns": ["SNES", "snes"],
            "extensions": ["sfc", "smc"],
            "rom_root": "Roms/SNES",
            "image_root": "Images/SNES",
            "default_core": "snes9x",
            "alternate_cores": [],
        },
        {
            "id": "PSX",
            "name": "PlayStation",
            "patterns": ["PSX"],
            "extensions": ["cue", "chd"],
            "rom_root": "Roms/PSX",
            "image_root": "Images/PSX",
            "default_core": "pcsx_rearmed",
            "alternate_cores": [],
        },
    ],
    "cores": [
        {
            "id": "snes9x",
            "display_name": "Snes9x",
            "type": "retroarch",
            "libretro_name": "snes9x",
            "file_name": "snes9x_libretro.so",
            "info_name": "snes9x_libretro.info",
            "config_folder": "Snes9x",
            "status": "packaged",
        },
        {
            "id": "pcsx_rearmed",
            "display_name": "PCSX ReARMed",
            "type": "retroarch",
            "libretro_name": "pcsx_rearmed",
            "file_name": "pcsx_rearmed_libretro.so",
            "info_name": "pcsx_rearmed_libretro.info",
            "config_folder": "PCSX-ReARMed",
            "status": "packaged",
        },
    ],
}


def scummvm_system(**edits) -> dict:
    system = {
        "id": "SCUMMVM",
        "name": "ScummVM",
        "patterns": ["SCUMMVM"],
        "extensions": ["scummvm"],
        "rom_root": "Roms/SCUMMVM",
        "image_root": "Images/SCUMMVM",
        "default_core": "scummvm",
        "alternate_cores": [],
        "icon_flat": "art/SCUMMVM.png",
    }
    system.update(edits)
    return system


def scummvm_core(**edits) -> dict:
    core = {
        "id": "scummvm",
        "display_name": "ScummVM",
        "type": "retroarch",
        "libretro_name": "scummvm",
        "file_name": "cores/scummvm_libretro.so",
        "info_name": "info/scummvm_libretro.info",
        "config_folder": "ScummVM",
    }
    core.update(edits)
    return core


def pak(provider: str, systems=None, cores=None, extensions=None) -> dict:
    return {
        "provider": provider,
        "provides": {
            "schema": 1,
            "systems": systems or [],
            "cores": cores or [],
            "system_extensions": extensions or [],
        },
    }


SCUMMVM_PAK = pak("mlp1/ScummVM.pak", [scummvm_system()], [scummvm_core()])

CASES: list[dict] = [
    {
        "name": "accept-new-system",
        "note": "the ordinary case: a new system id, no namespace collision.",
        "contributors": [SCUMMVM_PAK],
        "expect_diagnostics": [],
    },
    {
        "name": "accept-system-extension",
        "note": "system_extensions[] is the ONLY way to touch an existing "
                "system; the alternate core is appended, nothing is restated.",
        "contributors": [pak(
            "mlp1/MySnes.pak",
            cores=[scummvm_core(id="mysnescore", libretro_name="mysnescore",
                                config_folder="MySnes",
                                info_name="info/mysnescore_libretro.info",
                                file_name="cores/mysnescore_libretro.so",
                                display_name="My SNES Core")],
            extensions=[{"system_id": "SNES", "add_alternate_cores": ["mysnescore"]}],
        )],
        "expect_diagnostics": [],
    },
    {
        "name": "base-collision-system-id",
        "note": "a systems[] entry whose id already exists is a COLLISION, "
                "not an override. Overriding a first-party system is a "
                "non-goal.",
        "contributors": [pak("mlp1/Rogue.pak",
                             [scummvm_system(id="SNES")],
                             [scummvm_core()])],
        "expect_diagnostics": ["base-collision"],
    },
    {
        "name": "base-collision-pattern",
        "note": "P1-5: a unique id is not enough. Folder matching is "
                "first-match-wins, so claiming another system's pattern "
                "steals its ROM folder.",
        "contributors": [pak("mlp1/Rogue.pak",
                             [scummvm_system(patterns=["SCUMMVM", "snes"])],
                             [scummvm_core()])],
        "expect_diagnostics": ["base-collision"],
    },
    {
        "name": "base-collision-rom-root",
        "contributors": [pak("mlp1/Rogue.pak",
                             [scummvm_system(rom_root="Roms/SNES")],
                             [scummvm_core()])],
        "expect_diagnostics": ["base-collision"],
    },
    {
        "name": "base-collision-image-root",
        "contributors": [pak("mlp1/Rogue.pak",
                             [scummvm_system(image_root="Images/SNES")],
                             [scummvm_core()])],
        "expect_diagnostics": ["base-collision"],
        "note": "the system is refused for its image_root claim alone. Its "
                "core is untouched and stays in the catalog -- refusing a "
                "system does not retract a core another pak may extend a "
                "system with.",
    },
    {
        "name": "base-collision-core-id",
        "contributors": [pak("mlp1/Rogue.pak",
                             [scummvm_system(default_core="snes9x")],
                             [scummvm_core(id="snes9x")])],
        "expect_diagnostics": ["base-collision"],
        "note": "the core collides and is dropped; the system survives "
                "because default_core snes9x still resolves -- to the "
                "RELEASE core, which is exactly what should happen.",
    },
    {
        "name": "base-collision-config-folder",
        "note": "case-folded: 'snes9x' collides with the release 'Snes9x'. "
                "RetroArch would otherwise write both cores' saves into one "
                "FAT32 directory.",
        "contributors": [pak("mlp1/Rogue.pak",
                             [scummvm_system()],
                             [scummvm_core(config_folder="snes9x")])],
        "expect_diagnostics": ["base-collision", "default-core-unavailable"],
    },
    {
        "name": "base-collision-info-name",
        "note": "materialized .info FILENAMES share one merged directory, so "
                "the basename is a namespace even though the pak-relative "
                "paths differ.",
        "contributors": [pak("mlp1/Rogue.pak",
                             [scummvm_system()],
                             [scummvm_core(info_name="info/snes9x_libretro.info")])],
        "expect_diagnostics": ["base-collision", "default-core-unavailable"],
    },
    {
        "name": "contributor-collision-both-refused",
        "note": "D9: BOTH sides are refused. Never resolved by readdir order "
                "-- a contract that depends on directory iteration is not a "
                "contract.",
        "contributors": [
            pak("mlp1/Alpha.pak",
                [scummvm_system(id="ALPHA", patterns=["ALPHA"],
                                image_root="Images/ALPHA", default_core="alpha")],
                [scummvm_core(id="alpha", libretro_name="alpha",
                              config_folder="Alpha",
                              info_name="info/alpha_libretro.info")]),
            pak("mlp1/Beta.pak",
                [scummvm_system(id="BETA", patterns=["BETA"],
                                image_root="Images/BETA", default_core="beta")],
                [scummvm_core(id="beta", libretro_name="beta",
                              config_folder="Beta",
                              info_name="info/beta_libretro.info")]),
        ],
        "expect_diagnostics": ["contributor-collision", "contributor-collision"],
        "note_detail": "both systems claim rom_root Roms/SCUMMVM",
    },
    {
        "name": "casefold-contributor-collision",
        "note": "matching is already case-insensitive, so 'SCUMMVM' and "
                "'scummvm' are the same claim.",
        "contributors": [
            pak("mlp1/Alpha.pak",
                [scummvm_system(id="ALPHA", patterns=["SCUMMVM"],
                                rom_root="Roms/ALPHA", image_root="Images/ALPHA",
                                default_core="alpha")],
                [scummvm_core(id="alpha", libretro_name="alpha",
                              config_folder="Alpha",
                              info_name="info/alpha_libretro.info")]),
            pak("mlp1/Beta.pak",
                [scummvm_system(id="BETA", patterns=["scummvm"],
                                rom_root="Roms/BETA", image_root="Images/BETA",
                                default_core="beta")],
                [scummvm_core(id="beta", libretro_name="beta",
                              config_folder="Beta",
                              info_name="info/beta_libretro.info")]),
        ],
        "expect_diagnostics": ["contributor-collision", "contributor-collision"],
    },
    {
        "name": "default-core-unavailable",
        "note": "the pak's core is refused for a base collision, so its "
                "system is refused too. A tile that cannot launch is worse "
                "than no tile -- dependency cleanup is part of the merge.",
        "contributors": [pak("mlp1/ScummVM.pak",
                             [scummvm_system()],
                             [scummvm_core(config_folder="SNES9X")])],
        "expect_diagnostics": ["base-collision", "default-core-unavailable"],
    },
    {
        "name": "unknown-default-core",
        "note": "distinct from default-core-unavailable: nothing was refused, "
                "the manifest simply names a core that exists nowhere. "
                "Different diagnosis, different developer fix.",
        "contributors": [pak("mlp1/ScummVM.pak",
                             [scummvm_system(default_core="nosuchcore")],
                             [scummvm_core()])],
        "expect_diagnostics": ["unknown-default-core"],
    },
    {
        "name": "dangling-extension-system",
        "note": "T-5: an extension whose system is absent after merge is "
                "dropped and logged, not silently ignored.",
        "contributors": [pak("mlp1/MySnes.pak",
                             cores=[scummvm_core(id="mysnescore",
                                                 libretro_name="mysnescore",
                                                 config_folder="MySnes",
                                                 info_name="info/mysnescore_libretro.info")],
                             extensions=[{"system_id": "NOSUCH",
                                          "add_alternate_cores": ["mysnescore"]}])],
        "expect_diagnostics": ["dangling-extension-system"],
    },
    {
        "name": "dangling-alternate-core",
        "note": "the extension is ACCEPTED and the one bad name dropped: a "
                "single typo should not cost the developer the other entries.",
        "contributors": [pak("mlp1/MySnes.pak",
                             cores=[scummvm_core(id="mysnescore",
                                                 libretro_name="mysnescore",
                                                 config_folder="MySnes",
                                                 info_name="info/mysnescore_libretro.info")],
                             extensions=[{"system_id": "SNES",
                                          "add_alternate_cores": ["mysnescore", "ghost"]}])],
        "expect_diagnostics": ["dangling-alternate-core"],
    },
    {
        "name": "refusal-cascade",
        "note": "one pass is not enough. Alpha's core collides with the base, "
                "which refuses Alpha's system, which strands Beta's extension "
                "on that system. Cleanup iterates to a fixed point.",
        "contributors": [
            pak("mlp1/Alpha.pak",
                [scummvm_system(id="ALPHA", patterns=["ALPHA"],
                                rom_root="Roms/ALPHA", image_root="Images/ALPHA",
                                default_core="alpha")],
                [scummvm_core(id="alpha", libretro_name="alpha",
                              config_folder="Snes9x",
                              info_name="info/alpha_libretro.info")]),
            pak("mlp1/Beta.pak",
                cores=[scummvm_core(id="beta", libretro_name="beta",
                                    config_folder="Beta",
                                    info_name="info/beta_libretro.info")],
                extensions=[{"system_id": "ALPHA", "add_alternate_cores": ["beta"]}]),
        ],
        "expect_diagnostics": ["base-collision", "default-core-unavailable",
                               "dangling-extension-system"],
    },
]


def main() -> None:
    os.makedirs(os.path.dirname(OUT), exist_ok=True)
    out_cases = []
    for case in CASES:
        merged, diagnostics = content_model.merge(BASE, case["contributors"])
        got = sorted(d["reason"] for d in diagnostics)
        want = sorted(case["expect_diagnostics"])
        if got != want:
            raise SystemExit(
                f"{case['name']}: hand-asserted diagnostics {want} != "
                f"model output {got}. Fix the model or the assertion -- do "
                f"not regenerate past this."
            )
        entry = {k: v for k, v in case.items() if k != "expect_diagnostics"}
        entry["expect_diagnostics"] = case["expect_diagnostics"]
        entry["diagnostics"] = diagnostics
        entry["expected"] = merged
        entry["expected_sha256"] = canonical.canonical_sha256(merged)
        out_cases.append(entry)

    document = {
        "contract": "content-paks-v1",
        "note": "base + contributor inputs -> expected merged catalog. "
                "`expect_diagnostics` is hand-asserted; `expected` and "
                "`expected_sha256` are generated and must be reproduced "
                "byte-identically by Jawaka's compiler.",
        "base": BASE,
        "cases": out_cases,
    }
    with open(OUT, "w") as f:
        json.dump(document, f, indent=2)
        f.write("\n")
    print(f"Generated {len(out_cases)} merge fixtures.")


if __name__ == "__main__":
    main()
